# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19uutLAN3oPadKnBxXhTXUU0BirH7_HSi
"""

import zipfile, os

zip_path = "/content/pdf_positions.zip"   # adjust if the name is slightly different
extract_dir = "/content/pdf_positions"

os.makedirs(extract_dir, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall(extract_dir)

print("Extracted files:", os.listdir(extract_dir)[:10])

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import os
# import re
# 
# import pandas as pd
# import streamlit as st
# from pdfminer.high_level import extract_text
# 
# # ---------------------------------------------------------
# # CONFIG
# # ---------------------------------------------------------
# PDF_FOLDER = "/content/pdf_positions"   # folder with your 40 PDFs
# LANG_LIST = ["english","french","spanish","arabic","russian","chinese","portuguese","italian"]
# 
# # ---------------------------------------------------------
# # LOW-LEVEL CLEANING
# # ---------------------------------------------------------
# ILLEGAL_RE = re.compile(r"[\x00-\x08\x0B\x0C\x0E-\x1F]")
# 
# def clean_text(s: str) -> str:
#     if not isinstance(s, str):
#         return ""
#     s = ILLEGAL_RE.sub("", s)
#     mapping = {
#         "": "•", "▪": "•", "●": "•", "◦": "•",
#         "\uf0b7": "•", "\uf0a7": "•", "–": "-", "—": "-",
#     }
#     for k, v in mapping.items():
#         s = s.replace(k, v)
#     s = s.replace("\xad", "")
#     s = re.sub(r"[ \t]+", " ", s)
#     s = re.sub(r"\n{3,}", "\n\n", s)
#     return s.strip()
# 
# def extract_pdf_text(path: str) -> str:
#     text = extract_text(path)
#     return clean_text(text)
# 
# # ---------------------------------------------------------
# # SECTION & FIELD EXTRACTION
# # ---------------------------------------------------------
# def split_sections(text: str):
#     """Split by numbered headings like '1. General Information'."""
#     sections = {}
#     pattern = re.compile(r"^\s*(\d+)\.\s+(.+?)\s*:?\s*$", re.MULTILINE)
#     matches = list(pattern.finditer(text))
#     if not matches:
#         return sections
#     for i, m in enumerate(matches):
#         title = m.group(2).strip()
#         start = m.end()
#         end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
#         sections[title] = text[start:end].strip()
#     return sections
# 
# def find_section(sections: dict, keyword: str):
#     for t, c in sections.items():
#         if keyword.lower() in t.lower():
#             return c
#     return ""
# 
# def extract_organization(full_text: str) -> str:
#     lines = [l.strip() for l in full_text.splitlines() if l.strip()]
#     for i, line in enumerate(lines):
#         if "Fellowship Award Specification" in line:
#             if i + 1 < len(lines):
#                 return lines[i + 1]
#     return ""
# 
# def extract_global_fields(full_text: str):
#     """Try to get title, duty station, sector from the whole text."""
#     title = ""
#     duty = ""
#     sector = ""
#     m_title = re.search(r"Title:\s*(.+)", full_text, flags=re.I)
#     m_duty = re.search(r"Duty Station:\s*(.+)", full_text, flags=re.I)
#     m_sector = re.search(r"Sector of assignment:\s*(.+)", full_text, flags=re.I)
#     if m_title:
#         title = m_title.group(1).strip()
#     if m_duty:
#         duty = m_duty.group(1).strip()
#     if m_sector:
#         sector = m_sector.group(1).strip()
#     return title, duty, sector
# 
# # ---------------------------------------------------------
# # BULLET RECONSTRUCTION & CLASSIFICATION
# # ---------------------------------------------------------
# SUBSECTIONS = {
#     "education","work experience","professional experience",
#     "languages","language skills","other skills","technical skills",
#     "competencies","core competencies","core competencies skills"
# }
# 
# def rebuild_items(text: str):
#     """Rebuild bullet-like items as full sentences."""
#     if not text:
#         return []
#     lines = text.splitlines()
#     items = []
#     cur = ""
# 
#     def flush():
#         nonlocal cur
#         if cur.strip():
#             items.append(re.sub(r"\s+", " ", cur).strip())
#         cur = ""
# 
#     for raw in lines:
#         l = raw.strip()
#         if not l:
#             flush()
#             continue
#         if l.lower().rstrip(":") in SUBSECTIONS:
#             flush()
#             continue
#         if l.startswith(("•","-","*")):
#             flush()
#             l = l.lstrip("•-* \t")
#             cur = l
#         else:
#             if cur:
#                 cur += " " + l
#             else:
#                 cur = l
#     flush()
#     return items
# 
# DEGREE_KW = ["degree","bachelor","master","phd","education","university"]
# LANG_KW   = ["language","fluency","fluent","mother tongue","working knowledge"] + LANG_LIST
# EXP_KW    = ["experience","years","year","background"]
# SKILL_KW  = ["excel","power","analysis","statistics","python","gis","sql","stata","spss","skill","software"]
# COMP_KW   = ["competenc","teamwork","communication","leadership","planning","results focus"]
# 
# def classify_type(text: str) -> str:
#     low = text.lower()
#     if any(w in low for w in DEGREE_KW): return "degree"
#     if any(w in low for w in LANG_KW): return "language"
#     if any(w in low for w in EXP_KW): return "experience"
#     if any(w in low for w in SKILL_KW): return "skill"
#     if any(w in low for w in COMP_KW): return "competency"
#     return "other"
# 
# def tokenize(t: str):
#     return set(re.findall(r"[a-zA-Z]+", t.lower()))
# 
# def extract_languages_from_text(text: str):
#     low = text.lower()
#     found = set()
#     for lang in LANG_LIST:
#         if lang in low:
#             found.add(lang.capitalize())
#     return sorted(found)
# 
# # ---------------------------------------------------------
# # LOAD ALL POSITIONS (LOCAL) & CACHE
# # ---------------------------------------------------------
# @st.cache_data(show_spinner=True)
# def load_positions(pdf_folder: str = PDF_FOLDER):
#     files = sorted(f for f in os.listdir(pdf_folder) if f.lower().endswith(".pdf"))
#     positions = []
#     for fname in files:
#         code = os.path.splitext(fname)[0]
#         path = os.path.join(pdf_folder, fname)
#         try:
#             full_text = extract_pdf_text(path)
#         except Exception as e:
#             print("Error reading", code, ":", e)
#             continue
# 
#         sections = split_sections(full_text)
#         qual_text = find_section(sections, "Qualification")
#         duties_text = find_section(sections, "Duties")
# 
#         org = extract_organization(full_text)
#         title, duty, sector = extract_global_fields(full_text)
# 
#         qual_items = rebuild_items(qual_text)
#         duty_items = rebuild_items(duties_text)
# 
#         grouped = {"degree": [], "language": [], "experience": [], "skill": [], "competency": []}
#         for it in qual_items:
#             t = classify_type(it)
#             if t in grouped:
#                 grouped[t].append(it)
# 
#         degree_text = " ".join(grouped["degree"])
#         language_text = " ".join(grouped["language"])
#         skill_text = " ".join(grouped["skill"])
#         exp_text = " ".join(grouped["experience"])
#         comp_text = " ".join(grouped["competency"])
#         langs = extract_languages_from_text(language_text)
# 
#         positions.append({
#             "code": code,
#             "path": path,
#             "org": org,
#             "title": title,
#             "duty": duty,
#             "sector": sector,
#             "qual_grouped": grouped,
#             "duties": duty_items,
#             "degree_text": degree_text,
#             "language_text": language_text,
#             "skill_text": skill_text,
#             "exp_text": exp_text,
#             "comp_text": comp_text,
#             "languages": langs,
#         })
#     return positions
# 
# # ---------------------------------------------------------
# # MATCHING
# # ---------------------------------------------------------
# def set_overlap_score(user_set, pos_set):
#     if not user_set or not pos_set:
#         return 0.0
#     inter = user_set & pos_set
#     return len(inter) / len(user_set)
# 
# def rank_positions(positions, deg_str, lang_str, skill_str, interest_str):
#     deg_tokens  = tokenize(deg_str)
#     skill_tokens = tokenize(skill_str)
#     interest_tokens = tokenize(interest_str)
# 
#     user_langs = {l.strip().lower() for l in re.split(r"[;,]", lang_str) if l.strip()}
# 
#     results = []
#     for pos in positions:
#         deg_score   = set_overlap_score(deg_tokens, tokenize(pos["degree_text"]))
#         skill_score = set_overlap_score(skill_tokens, tokenize(pos["skill_text"]))
#         interest_corpus = " ".join(pos["duties"]) + " " + (pos["sector"] or "")
#         interest_score = set_overlap_score(interest_tokens, tokenize(interest_corpus))
# 
#         pos_langs_lower = {l.lower() for l in pos["languages"]}
#         if pos_langs_lower:
#             lang_inter = user_langs & pos_langs_lower
#             lang_score = len(lang_inter) / len(pos_langs_lower)
#         else:
#             lang_score = 0.0
# 
#         overall = 0.4*deg_score + 0.3*lang_score + 0.2*skill_score + 0.1*interest_score
# 
#         results.append({
#             "Position code": pos["code"],
#             "Organization": pos["org"],
#             "Duty station": pos["duty"],
#             "Sector": pos["sector"],
#             "Score": round(overall*100,1),
#             "Degree match %": round(deg_score*100,1),
#             "Language match %": round(lang_score*100,1),
#             "Skill match %": round(skill_score*100,1),
#             "Interest match %": round(interest_score*100,1),
#             "Languages (position)": ", ".join(pos["languages"]),
#             "PDF path": pos["path"],
#             "pos_obj": pos,
#         })
#     results_sorted = sorted(results, key=lambda r: r["Score"], reverse=True)
#     return results_sorted
# 
# # ---------------------------------------------------------
# # STREAMLIT UI
# # ---------------------------------------------------------
# st.set_page_config(page_title="UN Fellowship Matcher", layout="wide")
# st.title("🎯 UN Italian Fellowship Matcher")
# 
# st.write(
#     "This app compares your **degree, languages, skills and interests** "
#     "against all fellowship PDFs and ranks the positions by match."
# )
# 
# st.sidebar.header("Your profile")
# 
# deg_input = st.sidebar.text_input(
#     "Your degree / field",
#     value="environmental science, international relations, economics",
# )
# 
# lang_input = st.sidebar.text_input(
#     "Languages you speak",
#     value="English, French",
# )
# 
# skills_input = st.sidebar.text_area(
#     "Your main skills / tools",
#     value="data analysis, excel, project management, gis, statistics",
# )
# 
# interests_input = st.sidebar.text_area(
#     "Your thematic interests",
#     value="climate change, agriculture, water, governance",
# )
# 
# top_n = st.sidebar.slider("How many positions to show", min_value=5, max_value=40, value=15)
# 
# if st.sidebar.button("Find my best matches"):
#     with st.spinner("Loading and analyzing fellowship PDFs..."):
#         positions = load_positions()
# 
#         results = rank_positions(positions, deg_input, lang_input, skills_input, interests_input)
#         top = results[:top_n]
# 
#     st.subheader("Top matches")
#     table_df = pd.DataFrame([{
#         "Position code": r["Position code"],
#         "Organization": r["Organization"],
#         "Duty station": r["Duty station"],
#         "Sector": r["Sector"],
#         "Score %": r["Score"],
#         "Lang %": r["Language match %"],
#         "Deg %": r["Degree match %"],
#         "Skill %": r["Skill match %"],
#     } for r in top])
# 
#     st.dataframe(table_df, use_container_width=True)
# 
#     st.markdown("---")
#     st.subheader("Details")
# 
#     for r in top:
#         pos = r["pos_obj"]
#         with st.expander(f"{r['Position code']} – {r['Organization']} – {r['Duty station']} ({r['Score']}% match)"):
#             st.markdown(f"**Sector:** {pos['sector']}")
#             st.markdown(f"**PDF file (local path):** `{pos['path']}`")
# 
#             st.markdown("**📚 Degree-related requirements:**")
#             deg_lines = pos["qual_grouped"]["degree"]
#             if deg_lines:
#                 st.markdown("- " + "\n- ".join(deg_lines))
#             else:
#                 st.write("_No degree-related sentences detected._")
# 
#             st.markdown("**🗣 Language-related requirements:**")
#             lang_lines = pos["qual_grouped"]["language"]
#             if lang_lines:
#                 st.markdown("- " + "\n- ".join(lang_lines))
#             else:
#                 st.write("_No language-related sentences detected._")
# 
#             st.markdown("**🛠 Skills-related requirements:**")
#             skill_lines = pos["qual_grouped"]["skill"]
#             if skill_lines:
#                 st.markdown("- " + "\n- ".join(skill_lines))
#             else:
#                 st.write("_No explicit skill sentences detected._")
# 
#             st.markdown("**🧩 Experience-related requirements:**")
#             exp_lines = pos["qual_grouped"]["experience"]
#             if exp_lines:
#                 st.markdown("- " + "\n- ".join(exp_lines))
#             else:
#                 st.write("_No explicit experience sentences detected._")
# 
#             st.markdown("**🌐 Competency-related requirements:**")
#             comp_lines = pos["qual_grouped"]["competency"]
#             if comp_lines:
#                 st.markdown("- " + "\n- ".join(comp_lines))
#             else:
#                 st.write("_No explicit competency sentences detected._")
# 
#             st.markdown("**📌 Main duties / tasks:**")
#             if pos["duties"]:
#                 st.markdown("- " + "\n- ".join(pos["duties"]))
#             else:
#                 st.write("_No duties section found._")
# else:
#     st.info("Fill your profile on the left and click **'Find my best matches'**.")
#

!pip install streamlit pdfminer.six pandas

!wget -q -O cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!sudo dpkg -i cloudflared.deb

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 >/content/logs.txt 2>&1 &

!cloudflared tunnel --url http://localhost:8501 --no-autoupdate